"use client";
import { CalendarPlus, Check, LoaderCircle, X } from "lucide-react";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

type FollowUp = { id: string; scheduledAt: Date; reason: string; notes: string | null };
export function FollowUpPanel({ followUps, opportunityId }: { followUps: FollowUp[]; opportunityId: string }) {
 const dialog = useRef<HTMLDialogElement>(null); const router = useRouter(); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null);
 async function mutate(id:string, action:"complete"|"cancel") { setSaving(true); try { const r=await fetch(`/api/follow-ups/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})}); if(!r.ok) throw new Error(); toast.success(action==="complete"?"Follow-up concluído.":"Follow-up cancelado."); router.refresh(); } catch { toast.error("Não foi possível atualizar o follow-up."); } finally {setSaving(false);} }
 async function submit(e:React.FormEvent<HTMLFormElement>) { e.preventDefault(); const form=new FormData(e.currentTarget); setSaving(true); setError(null); try { const r=await fetch("/api/follow-ups",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({opportunityId,scheduledAt:new Date(String(form.get("scheduledAt"))).toISOString(),reason:form.get("reason"),notes:form.get("notes")})}); const p=await r.json() as {message?:string}; if(!r.ok){setError(p.message??"Não foi possível agendar.");return;} dialog.current?.close(); toast.success("Follow-up agendado."); router.refresh(); } catch {setError("Não foi possível agendar o follow-up.");} finally {setSaving(false);} }
 return <div className="space-y-4"><Button className="w-full" onClick={()=>dialog.current?.showModal()} type="button"><CalendarPlus aria-hidden="true"/>Agendar follow-up</Button>{followUps.map(f=><div className="rounded-md border border-border p-3" key={f.id}><p className="text-body-sm font-medium">{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(f.scheduledAt)}</p><p className="mt-1 text-body-sm text-text-secondary">{f.reason}</p><div className="mt-3 flex gap-2"><Button disabled={saving} onClick={()=>mutate(f.id,"complete")} size="sm" type="button" variant="secondary"><Check aria-hidden="true"/>Concluir</Button><Button disabled={saving} onClick={()=>mutate(f.id,"cancel")} size="sm" type="button" variant="secondary"><X aria-hidden="true"/>Cancelar</Button></div></div>)}<dialog className="w-[calc(100%-2rem)] max-w-lg rounded-lg border border-border bg-surface p-0 text-foreground shadow-level-2 backdrop:bg-black/40" ref={dialog}><form className="space-y-4 p-6" onSubmit={submit}><div><h2 className="text-heading-2 font-semibold">Agendar follow-up</h2><p className="mt-1 text-body-sm text-text-muted">O agendamento será confirmado somente ao salvar.</p></div><label className="block text-label">Data e hora<input className="mt-2 h-10 w-full rounded-sm border border-input bg-surface px-3" name="scheduledAt" required type="datetime-local" /></label><label className="block text-label">Motivo<input className="mt-2 h-10 w-full rounded-sm border border-input bg-surface px-3" name="reason" required /></label><label className="block text-label">Observação <span className="font-normal text-text-muted">(opcional)</span><Textarea className="mt-2" name="notes" /></label>{error?<p className="text-body-sm text-danger" role="alert">{error}</p>:null}<div className="flex justify-end gap-3"><Button onClick={()=>dialog.current?.close()} type="button" variant="secondary">Cancelar</Button><Button disabled={saving} type="submit">{saving?<LoaderCircle className="animate-spin"/>:null}Salvar</Button></div></form></dialog></div>;
}
